### ISSUE TITLE
How to unzip the dataset?

### ISSUE THREAD

**Issue by tjtanaa** [leddartech/pioneer.das.api#1]
Thank you very much for sharing the dataset.

I would like to know how should I unzip the dataset and organise the directories to use the api?

**Comment by jeanlucdeziel-leddartech** [comment]
Hi,

Downloading a single sequence will come in the form of a single zip. **The only thing you have to do is to unzip this file into a single directory.** It will contain several zip files (e.g. "pixell_bfc_ech.zip") and a few other things (intrinsics and extrinsics calibration directories, platform.yml). You don't need to unzip those files to use the API.
