### ISSUE TITLE
Link is dead

### ISSUE THREAD

**Issue by maxlem** [leddartech/pioneer.das.api#2]
Hey guys, what's up!
Gongrats for publishing das on GitHub!

They want me to present my profession at my son's school, I fgure why not presenting good ol das, my crypto stuff would bore them...

the Pixset download link is dead!
https://github.com/leddartech/pioneer.das.api/blob/master/dataset.leddartech.com

**Comment by jeanlucdeziel-leddartech** [comment]
Hi Maxime!

The link is just: dataset.leddartech.com

**Comment by jeanlucdeziel-leddartech** [comment]
Can you tell me where you got this link (https://github.com/leddartech/pioneer.das.api/blob/master/dataset.leddartech.com)?
We will make the correction if the link is wrong somewhere.
