### ISSUE TITLE
Installation Problem (platform Not found)

### ISSUE THREAD

**Issue by naderabdelaziz** [leddartech/pioneer.das.api#3]
Hello, 
I have a problem setting up the package that arises when running the first line of your examples:
from pioneer.das.api.platform import Platform

I get the same error that the module is not found. I tried to install the package using pip and I also tried the second method by cloning the repository and using the setup.py command. In both cases, I get the error shown below. I look forward to your response. Thank you.

OSError                                   Traceback (most recent call last)
<ipython-input-7-3381fc861e97> in <module>
----> 1 from pioneer.das.api.platform import Platform
      2 
      3 

c:\windows\system32\pioneer.das.api\pioneer\das\api\platform.py in <module>
      2 from pioneer.common.logging_manager import LoggingManager
      3 from pioneer.das.api.datasources import AbstractDatasource
----> 4 from pioneer.das.api.datasources import virtual_datasources
      5 from pioneer.das.api.samples.sample import Sample
      6 from pioneer.das.api.sensors import Sensor

c:\windows\system32\pioneer.das.api\pioneer\das\api\datasources\virtual_datasources\__init__.py in <module>
      1 from pioneer.das.api.datasources.virtual_datasources.virtual_datasource import VirtualDatasource
----> 2 from pioneer.das.api.datasources.virtual_datasources.cylindrical_projection import FlirCylindricalProjection
      3 from pioneer.das.api.datasources.virtual_datasources.echoes_from_traces import Echoes_from_Traces
      4 from pioneer.das.api.datasources.virtual_datasources.echoes_with_pulses import EchoesWithPulses
      5 from pioneer.das.api.datasources.virtual_datasources.hdr_waveform import HDRWaveform

c:\windows\system32\pioneer.das.api\pioneer\das\api\datasources\virtual_datasources\cylindrical_projection.py in <module>
      3 from pioneer.das.api.datasources.virtual_datasources import VirtualDatasource
      4 from pioneer.das.api.interpolators import nearest_interpolator
----> 5 from pioneer.das.api.samples import ImageCylinder
      6 
      7 import numpy as np

c:\windows\system32\pioneer.das.api\pioneer\das\api\samples\__init__.py in <module>
----> 1 from pioneer.das.api.samples.annotations import *
      2 from pioneer.das.api.samples.echo import Echo
      3 from pioneer.das.api.samples.echo_xyzit import EchoXYZIT
      4 from pioneer.das.api.samples.fast_trace import FastTrace
      5 from pioneer.das.api.samples.image import Image

c:\windows\system32\pioneer.das.api\pioneer\das\api\samples\annotations\__init__.py in <module>
      1 from pioneer.das.api.interpolators import nearest_interpolator
----> 2 from pioneer.das.api.samples.annotations.box_3d import Box3d
      3 from pioneer.das.api.samples.annotations.box_2d import Box2d
      4 from pioneer.das.api.samples.annotations.poly_2d import Poly2d
      5 from pioneer.das.api.samples.annotations.seg_2d import Seg2d

c:\windows\system32\pioneer.das.api\pioneer\das\api\samples\annotations\box_3d.py in <module>
----> 1 from pioneer.common import platform, linalg, IoU3d
      2 from pioneer.common.logging_manager import LoggingManager
      3 from pioneer.common import platform as platform_utils
      4 from pioneer.das.api import categories
      5 from pioneer.das.api.samples.sample import Sample

c:\users\nader.abdelaziz\appdata\local\continuum\anaconda3\lib\site-packages\pioneer\common\IoU3d.py in <module>
----> 1 from shapely.geometry import Polygon
      2 
      3 import numpy as np
      4 
      5 def _tf_rot2d(theta, pt):

c:\users\nader.abdelaziz\appdata\local\continuum\anaconda3\lib\site-packages\shapely\geometry\__init__.py in <module>
      2 """
      3 
----> 4 from .base import CAP_STYLE, JOIN_STYLE
      5 from .geo import box, shape, asShape, mapping
      6 from .point import Point, asPoint

c:\users\nader.abdelaziz\appdata\local\continuum\anaconda3\lib\site-packages\shapely\geometry\base.py in <module>
     17 
     18 from shapely.affinity import affine_transform
---> 19 from shapely.coords import CoordinateSequence
     20 from shapely.errors import WKBReadingError, WKTReadingError
     21 from shapely.geos import WKBWriter, WKTWriter

c:\users\nader.abdelaziz\appdata\local\continuum\anaconda3\lib\site-packages\shapely\coords.py in <module>
      6 from ctypes import byref, c_double, c_uint
      7 
----> 8 from shapely.geos import lgeos
      9 from shapely.topology import Validating
     10 

c:\users\nader.abdelaziz\appdata\local\continuum\anaconda3\lib\site-packages\shapely\geos.py in <module>
    152     if os.getenv('CONDA_PREFIX', ''):
    153         # conda package.
--> 154         _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
    155     else:
    156         try:

~\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: [WinError 126] The specified module could not be found

**Comment by pierremerriaux-leddartech** [comment]
Hi @naderabdelaziz 

Could you confirm you use python 3.6 ? Could you try in python3 interpreter : from shapely.geometry import Polygon
and check also the Shapely version version ? On my side, I get: 
~/project/pioneer$ pip3 list|grep Shapely
Shapely                       1.7.0

Thanks
Pierre

**Comment by jfparentledartech** [comment]
Hi,
You can also try to install shapely from conda-forge:
```
conda config --add channels conda-forge
conda install shapely
```

**Comment by naderabdelaziz** [comment]
> Hi,
> You can also try to install shapely from conda-forge:
> 
> ```
> conda config --add channels conda-forge
> conda install shapely
> ```


Hi, 

That actually solved the problem for me through the anaconda terminal.  I appreciate the help. 

Thanks, 
Nader.
