### ISSUE TITLE
number of points clouds in a frame for leddartech solid state lidar

### ISSUE THREAD

**Issue by gaopenggang** [leddartech/pioneer.das.api#7]
I try to output the number of pixell_cloud.shape and ouster_cloud.shape in a frame using  the code shown as folows.  I am not familiar with solid state lidar. Does it means that there are  about 500 points clouds in a frame for the flash solid state lidar? 
```
     pf = platform.Platform(_dataset, ignore=_ignore)
     pixell_pc = pf.sensors['pixell_bfc']['ech']
     ouster64_pc = pf.sensors['ouster64_bfc']['xyzit']
     for i in range(len(pixell_pc)):
         pixell_pcloud = pixell_pc[i].point_cloud(undistort=True)
         print("i: ", i , " pixell_cloud.shape: ", pixell_pcloud.shape)
     for j in range(len(ouster64_pc)):
         ouster_pcloud = ouster64_pc[j].point_cloud(undistort=True)
         print("j: ", j , " ouster_cloud.shape: ", ouster_pcloud.shape)
```

**Comment by jeanlucdeziel-leddartech** [comment]
Hi,

Yes that's what it means. The point_cloud() method returns a Nx3 numpy array where N is the number of points in the point cloud. The 3 corresponds to x y z coordinates.

JL

**Comment by gaopenggang** [comment]
Thank you a lot.
